version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=myDb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './dump:/docker-entrypoint-initdb.d'
      - './docker/volume/mysql:/var/lib/mysql'
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin    
    ports:
      - 8000:80
    environment:      
      - MYSQL_ROOT_PASSWORD=root
      - PMA_ARBITRARY=1
    links:
      - mysql
